[2023-10-30T22:14:05.003+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_http_request_weekly.send_http_request manual__2023-10-30T16:44:01.393232+00:00 [queued]>
[2023-10-30T22:14:05.010+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_http_request_weekly.send_http_request manual__2023-10-30T16:44:01.393232+00:00 [queued]>
[2023-10-30T22:14:05.010+0530] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-10-30T22:14:05.026+0530] {taskinstance.py:1327} INFO - Executing <Task(SimpleHttpOperator): send_http_request> on 2023-10-30 16:44:01.393232+00:00
[2023-10-30T22:14:05.030+0530] {standard_task_runner.py:57} INFO - Started process 198671 to run task
[2023-10-30T22:14:05.034+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'send_http_request_weekly', 'send_http_request', 'manual__2023-10-30T16:44:01.393232+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/send_mail_dag.py', '--cfg-path', '/tmp/tmpo15w0fcg']
[2023-10-30T22:14:05.036+0530] {standard_task_runner.py:85} INFO - Job 3: Subtask send_http_request
[2023-10-30T22:14:05.077+0530] {task_command.py:410} INFO - Running <TaskInstance: send_http_request_weekly.send_http_request manual__2023-10-30T16:44:01.393232+00:00 [running]> on host jay-TUF-Gaming-FX505DY
[2023-10-30T22:14:05.158+0530] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='send_http_request_weekly' AIRFLOW_CTX_TASK_ID='send_http_request' AIRFLOW_CTX_EXECUTION_DATE='2023-10-30T16:44:01.393232+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-30T16:44:01.393232+00:00'
[2023-10-30T22:14:05.159+0530] {http.py:123} INFO - Calling HTTP method
[2023-10-30T22:14:05.164+0530] {base.py:73} INFO - Using connection ID 'http_default' for task execution.
[2023-10-30T22:14:07.054+0530] {http.py:181} ERROR - HTTP error: NOT FOUND
[2023-10-30T22:14:07.054+0530] {http.py:182} ERROR - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

[2023-10-30T22:14:07.066+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/jay/anaconda3/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 179, in check_response
    response.raise_for_status()
  File "/home/jay/anaconda3/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://www.httpbin.org/https://example.com/api/endpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jay/anaconda3/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 125, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/jay/anaconda3/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 169, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/home/jay/anaconda3/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 222, in run_and_check
    self.check_response(response)
  File "/home/jay/anaconda3/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 183, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 404:NOT FOUND
[2023-10-30T22:14:07.071+0530] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=send_http_request_weekly, task_id=send_http_request, execution_date=20231030T164401, start_date=20231030T164405, end_date=20231030T164407
[2023-10-30T22:14:07.184+0530] {standard_task_runner.py:109} ERROR - Failed to execute job 3 for task send_http_request (404:NOT FOUND; 198671)
[2023-10-30T22:14:07.214+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-30T22:14:07.239+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
